name: Build & Release

on:
    push:
        branches:
            - main
            - develop

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v3

        - name: Set up Python
          run: uv python install

        - name: Build the package
          run: uv build

        - name: Store the package
          uses: actions/upload-artifact@v4
          with:
            name: python-package-distributions
            path: dist/