name: Build & Release

on:
    push:
        branches:
            - main
            - develop

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v3

        - name: Set up Python
          run: uv python install

        - name: Build the package
          run: uv build

        - name: Store the package
          uses: actions/upload-artifact@v4
          with:
            name: conditions-ai
            path: dist/
    
    release:
        name: Release
        runs-on: ubuntu-latest

        needs: build

        steps:
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v3

        - name: Set up Python
          run: uv python install

        - name: Install twine
          run: uv add twine

        - name: Download build artifact
          uses: actions/download-artifact@v4
          with:
            name: conditions-ai

        - name: Publish to PyPI
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          run: uv python -m twine upload dist/*