name: Run Unit Test via Pytest

on:
    workflow_dispatch:
    # workflow_run:
    #   workflows: ["Build and Publish"]
    #   types:
    #     - completed

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv add conditions-ai>0.1 pytest

      - name: Run tests
        run: uv run pytest tests/
